version: '3.9'

services:
  backend:
    build: ./api
    container_name: backend
    volumes:
      - ./saved_models:/app/../saved_models  # Mount your saved model
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
